import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDF = async (records, user) => {
    // Create PDF in landscape orientation (short bond paper)
    const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4' // Short bond paper size
    });

    // Add header
    pdf.setFontSize(20);
    pdf.setTextColor(40, 40, 40);
    pdf.text('BLOOD SUGAR RECORDS REPORT', 105, 20, { align: 'center' });

    // Add patient info
    pdf.setFontSize(10);
    pdf.setTextColor(80, 80, 80);
    pdf.text(`Patient: ${user?.name || 'User'}`, 20, 35);
    pdf.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 42);
    pdf.text(`Total Records: ${records.length}`, 20, 49);

    // Add summary section if there are records
    if (records.length > 0) {
        const stats = calculateStats(records);
        pdf.text(`Average: ${stats.average} mg/dL`, 150, 35);
        pdf.text(`Highest: ${stats.max} mg/dL`, 150, 42);
        pdf.text(`Lowest: ${stats.min} mg/dL`, 150, 49);
    }

    // Add table headers
    pdf.setFillColor(240, 240, 240);
    pdf.rect(20, 60, 250, 10, 'F');
    pdf.setFontSize(9);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont(undefined, 'bold');

    const headers = ['Date', 'Before Breakfast', 'After Breakfast', 'After Lunch', 'After Dinner', 'Breakfast Meal', 'Lunch Meal', 'Dinner Meal'];
    const columnWidths = [25, 25, 25, 25, 25, 45, 45, 45];
    let xPosition = 20;

    headers.forEach((header, index) => {
        pdf.text(header, xPosition + 2, 67);
        xPosition += columnWidths[index];
    });

    // Add records
    pdf.setFont(undefined, 'normal');
    let yPosition = 75;

    records.forEach((record, index) => {
        if (yPosition > 180) { // Add new page if running out of space
            pdf.addPage();
            yPosition = 20;

            // Add header on new page
            pdf.setFontSize(10);
            pdf.setTextColor(80, 80, 80);
            pdf.text(`Patient: ${user?.name || 'User'}`, 20, yPosition);
            pdf.text(`Page ${pdf.getNumberOfPages()}`, 250, yPosition);
            yPosition = 30;
        }

        // Alternate row colors
        if (index % 2 === 0) {
            pdf.setFillColor(250, 250, 250);
        } else {
            pdf.setFillColor(255, 255, 255);
        }
        pdf.rect(20, yPosition - 5, 250, 8, 'F');

        // Record data
        pdf.setFontSize(8);
        xPosition = 20;

        const rowData = [
            formatDate(record.date),
            record.beforeBreakfast || '-',
            record.afterBreakfast || '-',
            record.afterLunch || '-',
            record.afterDinner || '-',
            record.breakfastMeal || '-',
            record.lunchMeal || '-',
            record.dinnerMeal || '-'
        ];

        rowData.forEach((data, colIndex) => {
            // Truncate long text
            const displayText = data.length > 20 ? data.substring(0, 20) + '...' : data;

            // Color code blood sugar readings
            if (colIndex >= 1 && colIndex <= 4 && data !== '-') {
                const value = parseInt(data);
                if (value < 70) {
                    pdf.setTextColor(220, 38, 38); // Red for low
                } else if (value > 140) {
                    pdf.setTextColor(220, 38, 38); // Red for high
                } else {
                    pdf.setTextColor(0, 0, 0); // Black for normal
                }
            } else {
                pdf.setTextColor(0, 0, 0);
            }

            pdf.text(displayText, xPosition + 2, yPosition);
            xPosition += columnWidths[colIndex];
        });

        yPosition += 8;
    });

    // Add footer
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(100, 100, 100);
        pdf.text(`Generated by GlucoseTracker - Page ${i} of ${pageCount}`, 105, 200, { align: 'center' });
    }

    // Save the PDF
    pdf.save(`blood-sugar-records-${new Date().toISOString().split('T')[0]}.pdf`);
};

const calculateStats = (records) => {
    const allReadings = records.flatMap(record => [
        record.beforeBreakfast,
        record.afterBreakfast,
        record.afterLunch,
        record.afterDinner
    ].filter(val => val && val.trim() !== '').map(Number));

    if (allReadings.length === 0) {
        return { average: 'N/A', max: 'N/A', min: 'N/A' };
    }

    const average = allReadings.reduce((a, b) => a + b, 0) / allReadings.length;
    const max = Math.max(...allReadings);
    const min = Math.min(...allReadings);

    return {
        average: average.toFixed(1),
        max,
        min
    };
};

const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric'
    });
};